// Command gencss turns the vendored github-markdown-css light and dark files
// into one stylesheet whose colors are CSS variables, plus a light and a dark
// palette for those variables, so that a theme can recolor the Markdown body
// by setting variables instead of overriding every rule.
//
// The two files have the same rules in the same order and differ only in
// colors, so each color in the light file is paired with the color at the
// same place in the dark file.
package main

import (
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
)

var colorRe = regexp.MustCompile(`#[0-9a-fA-F]{3,8}\b`)

// Names for the colors a theme is most likely to change, by their light and
// dark values: the same light color can stand for different things, such as
// #f6f8fa for the muted background and for a syntax color. The rest are
// named after their light value.
var names = map[[2]string]string{
	{"#1f2328", "#f0f6fc"}:     "fgColor-default",
	{"#ffffff", "#0d1117"}:     "bgColor-default",
	{"#f6f8fa", "#151b23"}:     "bgColor-muted",
	{"#59636e", "#9198a1"}:     "fgColor-muted",
	{"#0969da", "#4493f8"}:     "fgColor-accent",
	{"#0969da", "#1f6feb"}:     "focus-outlineColor",
	{"#d1d9e0", "#3d444d"}:     "borderColor-default",
	{"#d1d9e0b3", "#3d444db3"}: "borderColor-muted",
	{"#818b981f", "#656c7633"}: "bgColor-neutral-muted",
}

func main() {
	if len(os.Args) != 4 {
		log.Fatal("usage: gencss LIGHT DARK OUT")
	}
	light := read(os.Args[1])
	dark := read(os.Args[2])

	lightColors := colorRe.FindAllString(light, -1)
	darkColors := colorRe.FindAllString(dark, -1)
	if len(lightColors) != len(darkColors) {
		log.Fatalf("color count differs: %d vs %d", len(lightColors), len(darkColors))
	}
	if shape(light) != shape(dark) {
		log.Fatal("light and dark files differ in more than colors")
	}

	// name -> dark value; a light color paired with different dark colors
	// gets one variable per pair
	vars := map[string][2]string{}
	varFor := func(l, d string) string {
		base, ok := names[[2]string{strings.ToLower(l), strings.ToLower(d)}]
		if !ok {
			base = "md-" + strings.TrimPrefix(strings.ToLower(l), "#")
		}
		name := base
		for i := 2; ; i++ {
			v, ok := vars[name]
			if !ok {
				vars[name] = [2]string{l, d}
				return name
			}
			if v[1] == d {
				return name
			}
			name = fmt.Sprintf("%s-%d", base, i)
		}
	}

	i := 0
	body := colorRe.ReplaceAllStringFunc(light, func(l string) string {
		name := varFor(l, darkColors[i])
		i++
		return "var(--" + name + ")"
	})
	body = strings.Replace(body, "/* light */\n", "", 1)
	body = strings.Replace(body, "  color-scheme: light;\n", "", 1)

	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("/* Generated by hack/gencss from github-markdown-css. Do not edit. */\n\n")
	palette := func(selector, scheme string, idx int) {
		fmt.Fprintf(&b, "%s {\n  color-scheme: %s;\n", selector, scheme)
		for _, k := range keys {
			fmt.Fprintf(&b, "  --%s: %s;\n", k, vars[k][idx])
		}
		b.WriteString("}\n\n")
	}
	palette(`:root, :root[data-mode="light"]`, "light", 0)
	palette(`:root[data-mode="dark"]`, "dark", 1)
	b.WriteString(body)

	if err := os.WriteFile(os.Args[3], []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}

func read(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	return string(b)
}

// shape is the stylesheet with its colors and color scheme blanked out.
func shape(css string) string {
	css = colorRe.ReplaceAllString(css, "#")
	return regexp.MustCompile(`light|dark`).ReplaceAllString(css, "")
}
