// Command gencss turns the vendored github-markdown-css light and dark files
// into one stylesheet whose colors are CSS variables, plus a light and a dark
// palette for those variables, so that a theme can recolor the Markdown body
// by setting variables instead of overriding every rule.
//
// The two files have the same rules in the same order and differ only in
// colors, so each color in the light file is paired with the color at the
// same place in the dark file.
package main

import (
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
)

var colorRe = regexp.MustCompile(`#[0-9a-fA-F]{3,8}\b`)

// Names for the colors, by their light and dark values: the same light color
// can stand for different things, such as #0969da for the accent and for the
// focus ring. Every color must have a name, so that a new color upstream is
// named before it reaches a theme.
var names = map[[2]string]string{
	{"#1f2328", "#f0f6fc"}:     "fgColor-default",
	{"#ffffff", "#0d1117"}:     "bgColor-default",
	{"#f6f8fa", "#151b23"}:     "bgColor-muted",
	{"#59636e", "#9198a1"}:     "fgColor-muted",
	{"#0969da", "#4493f8"}:     "fgColor-accent",
	{"#0969da", "#1f6feb"}:     "focus-outlineColor",
	{"#d1d9e0", "#3d444d"}:     "borderColor-default",
	{"#d1d9e0b3", "#3d444db3"}: "borderColor-muted",
	{"#818b981f", "#656c7633"}: "bgColor-neutral-muted",
	{"#1a7f37", "#3fb950"}:     "fgColor-success",
	{"#9a6700", "#d29922"}:     "fgColor-attention",
	{"#d1242f", "#f85149"}:     "fgColor-danger",
	{"#8250df", "#ab7df8"}:     "fgColor-done",
	{"#1a7f37", "#238636"}:     "borderColor-success-emphasis",
	{"#9a6700", "#9e6a03"}:     "borderColor-attention-emphasis",
	{"#cf222e", "#da3633"}:     "borderColor-danger-emphasis",
	{"#8250df", "#8957e5"}:     "borderColor-done-emphasis",
	{"#fff8c5", "#bb800926"}:   "bgColor-attention-muted",
}

// derived colors are left out of the palettes and fall back to a base color,
// so that a theme setting only the base color changes them too. GitHub's
// own values for them are in themes/github.css.
var derived = map[string]string{
	"borderColor-success-emphasis":   "var(--fgColor-success)",
	"borderColor-attention-emphasis": "var(--fgColor-attention)",
	"borderColor-danger-emphasis":    "var(--fgColor-danger)",
	"borderColor-done-emphasis":      "var(--fgColor-done)",
	"bgColor-attention-muted":        "color-mix(in srgb, var(--fgColor-attention) 20%, transparent)",
}

// deadRule matches a rule for GitHub's syntax classes (.pl-*) or .absent,
// which gh-mini never emits: code is highlighted by chroma.
var deadRule = regexp.MustCompile(`(?m)^(?:\.markdown-body (?:\.pl-[\w-]+|\.absent)(?: \.pl-[\w-]+)*(?:,\n| \{))+[^{}]*\}\n+`)

func main() {
	if len(os.Args) != 4 {
		log.Fatal("usage: gencss LIGHT DARK OUT")
	}
	light := deadRule.ReplaceAllString(read(os.Args[1]), "")
	dark := deadRule.ReplaceAllString(read(os.Args[2]), "")

	lightColors := colorRe.FindAllString(light, -1)
	darkColors := colorRe.FindAllString(dark, -1)
	if len(lightColors) != len(darkColors) {
		log.Fatalf("color count differs: %d vs %d", len(lightColors), len(darkColors))
	}
	if shape(light) != shape(dark) {
		log.Fatal("light and dark files differ in more than colors")
	}

	// name -> dark value; a light color paired with different dark colors
	// gets one variable per pair
	vars := map[string][2]string{}
	varFor := func(l, d string) string {
		name, ok := names[[2]string{strings.ToLower(l), strings.ToLower(d)}]
		if !ok {
			log.Fatalf("no name for the color %s (light) / %s (dark)", l, d)
		}
		vars[name] = [2]string{l, d}
		if fallback, ok := derived[name]; ok {
			return name + ", " + fallback
		}
		return name
	}

	i := 0
	body := colorRe.ReplaceAllStringFunc(light, func(l string) string {
		name := varFor(l, darkColors[i])
		i++
		return "var(--" + name + ")"
	})
	body = strings.Replace(body, "/* light */\n", "", 1)
	body = strings.Replace(body, "  color-scheme: light;\n", "", 1)

	keys := make([]string, 0, len(vars))
	for k := range vars {
		if _, ok := derived[k]; !ok {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("/* Generated by hack/gencss from github-markdown-css. Do not edit. */\n\n")
	palette := func(selector, scheme string, idx int) {
		fmt.Fprintf(&b, "%s {\n  color-scheme: %s;\n", selector, scheme)
		for _, k := range keys {
			fmt.Fprintf(&b, "  --%s: %s;\n", k, vars[k][idx])
		}
		b.WriteString("}\n\n")
	}
	palette(`:root, :root[data-mode="light"]`, "light", 0)
	palette(`:root[data-mode="dark"]`, "dark", 1)
	b.WriteString(body)

	if err := os.WriteFile(os.Args[3], []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}

func read(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	return string(b)
}

// shape is the stylesheet with its colors and color scheme blanked out.
func shape(css string) string {
	css = colorRe.ReplaceAllString(css, "#")
	return regexp.MustCompile(`light|dark`).ReplaceAllString(css, "")
}
